# docs: https://grafana.com/docs/grafana/latest/administration/provisioning/#data-sources

# config file version
apiVersion: 1

# list of datasources to insert/update depending on what's available in the
# datbase
datasources:
   # <string, required> name of the datasource. Required
 - name: Grafana ClickHouse
   # <string, required> datasource type. Required
   type: grafana-clickhouse-datasource
   # <int> org id. will default to orgId 1 if not specified
   orgId: 1
   # <bool> mark as default datasource. Max one per org
   isDefault: false
   # <string> version
   version: 1
   # <bool> allow users to edit datasources from the UI.
   editable: false

   # <map> fields that will be converted to json and stored in json_data
   jsonData:
     protocol: http
     port: 8123
     server: gstma-clickhouse
     tlsSkipVerify: false

